//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCopyright("Copyright © Tripp\'n Technology, LLC. 2012")]
[assembly: AssemblyFileVersion("1.0.1.615")]
[assembly: AssemblyInformationalVersion("1.0.1.615")]
[assembly: AssemblyTitle("Visual Studio Regular Expression validator")]
[assembly: AssemblyVersion("1.0.1.615")]
[assembly: AssemblyDescription("Visual Studio Regular Expression validator")]
[assembly: AssemblyProduct("Visual Studio Regular Expression validator")]


